<a href="https://colab.research.google.com/github/mikszn/POI-Ex.-4/blob/main/POI_Ex_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [2]:
features = pd.read_csv('textures_data.csv', sep=' ')

In [3]:
data = np.array(features)
X = data[:,:-1].astype('float64') # wyodrębnienie cech (jako floaty)
Y = data[:,-1]    # wyodrębnienie etykiet

In [4]:
# Kodowanie całkowitoliczbowe
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(Y)

# Kodowanie jeden z n
oneshot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
oneshot_encoded = oneshot_encoder.fit_transform(integer_encoded)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [5]:
x_train, x_test, y_train, y_test = train_test_split(X, oneshot_encoded, test_size=0.3)

In [6]:
model = Sequential()
model.add(Dense(10, input_dim=72, activation='sigmoid'))
model.add(Dense(4, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                730       
                                                                 
 dense_1 (Dense)             (None, 4)                 44        
                                                                 
Total params: 774
Trainable params: 774
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.fit(x_train, y_train, epochs=100, batch_size=10, shuffle=True)

Epoch 1/100
14/14 [==============================] - 5s 4ms/step - loss: 1.3793 - accuracy: 0.5299
Epoch 2/100
14/14 [==============================] - 0s 4ms/step - loss: 1.2873 - accuracy: 0.5373
Epoch 3/100
14/14 [==============================] - 0s 3ms/step - loss: 1.2270 - accuracy: 0.5373
Epoch 4/100
14/14 [==============================] - 0s 3ms/step - loss: 1.1817 - accuracy: 0.5373
Epoch 5/100
14/14 [==============================] - 0s 3ms/step - loss: 1.1438 - accuracy: 0.5373
Epoch 6/100
14/14 [==============================] - 0s 4ms/step - loss: 1.1192 - accuracy: 0.5373
Epoch 7/100
14/14 [==============================] - 0s 3ms/step - loss: 1.0808 - accuracy: 0.5373
Epoch 8/100
14/14 [==============================] - 0s 3ms/step - loss: 1.0630 - accuracy: 0.5373
Epoch 9/100
14/14 [==============================] - 0s 4ms/step - loss: 1.0359 - accuracy: 0.5597
Epoch 10/100
14/14 [==============================] - 0s 3ms/step - loss: 1.0057 - accuracy: 0.7313
Epoch 11/

In [8]:
y_pred = model.predict(x_test)
y_pred_int = np.argmax(y_pred, axis=1)
y_test_int = np.argmax(y_test, axis=1)
cm = confusion_matrix(y_test_int, y_pred_int)
print(cm)

2/2 [==============================] - 0s 6ms/step
[[20  0  0  0]
 [ 0 12  0  0]
 [ 0  0 12  0]
 [ 0  0  0 14]]
